apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: custom-dependency-spring-kube-config-demo-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "configmaps"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-dependency-spring-kube-config-demo-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: custom-dependency-spring-kube-config-demo-sa
    namespace: default
roleRef:
  kind: Role
  name: custom-dependency-spring-kube-config-demo-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-dependency-spring-kube-config-demo-sa
  namespace: default