spring:
  application:
    name: standard-dependency-spring-kube-config-demo

server:
  port: 9091

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"